AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket for static website hosting without using lambda functions

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-your-s3-bucket-name'
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'


  NewObjectHtmlFile:
    Type: 'Custom::S3PutObject'
    Properties:
      Target:
        Bucket: !Ref S3Bucket
        Key: 'index.html'
      Body: |
        <html>
          <head>
            <title>My Static Website</title>
          </head>
          <body>
            <h1>Hello from AWS S3 Static Website!</h1>
          </body>
        </html>

Outputs:
  WebsiteURL:
    Value: !GetAtt S3Bucket.WebsiteURL
    Description: URL of the static website
